In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [3]:
df_train.describe()

1stFlrSF     2ndFlrSF    3SsnPorch  BedroomAbvGr   BsmtFinSF1  \
count  1460.000000  1460.000000  1460.000000   1460.000000  1460.000000   
mean   1162.626712   346.992466     3.409589      2.866438   443.639726   
std     386.587738   436.528436    29.317331      0.815778   456.098091   
min     334.000000     0.000000     0.000000      0.000000     0.000000   
25%     882.000000     0.000000     0.000000      2.000000     0.000000   
50%    1087.000000     0.000000     0.000000      3.000000   383.500000   
75%    1391.250000   728.000000     0.000000      3.000000   712.250000   
max    4692.000000  2065.000000   508.000000      8.000000  5644.000000   

        BsmtFinSF2  BsmtFullBath  BsmtHalfBath    BsmtUnfSF  EnclosedPorch  \
count  1460.000000   1460.000000   1460.000000  1460.000000    1460.000000   
mean     46.549315      0.425342      0.057534   567.240411      21.954110   
std     161.319273      0.518911      0.238753   441.866955      61.119149   
min       0.000000      0.000000      0.000000     0.000000       0.000000   
25%       0.000000      0.000000      0.000000   223.000000       0.000000   
50%       0.000000      0.000000      0.000000   477.500000       0.000000   
75%       0.000000      1.000000      0.000000   808.000000       0.000000   
max    1474.000000      3.000000      2.000000  2336.000000     552.000000   

           ...        SaleType_ConLI  SaleType_ConLw  SaleType_New  \
count      ...           1460.000000     1460.000000   1460.000000   
mean       ...              0.003425        0.003425      0.083562   
std        ...              0.058440        0.058440      0.276824   
min        ...              0.000000        0.000000      0.000000   
25%        ...              0.000000        0.000000      0.000000   
50%        ...              0.000000        0.000000      0.000000   
75%        ...              0.000000        0.000000      0.000000   
max        ...              1.000000        1.000000      1.000000   

       SaleType_Oth  SaleType_WD  Street_Grvl  Street_Pave  Utilities_AllPub  \
count   1460.000000  1460.000000  1460.000000  1460.000000       1460.000000   
mean       0.002055     0.867808     0.004110     0.995890          0.999315   
std        0.045299     0.338815     0.063996     0.063996          0.026171   
min        0.000000     0.000000     0.000000     0.000000          0.000000   
25%        0.000000     1.000000     0.000000     1.000000          1.000000   
50%        0.000000     1.000000     0.000000     1.000000          1.000000   
75%        0.000000     1.000000     0.000000     1.000000          1.000000   
max        1.000000     1.000000     1.000000     1.000000          1.000000   

       Utilities_NoSeWa      SalePrice  
count       1460.000000    1460.000000  
mean           0.000685  180921.195890  
std            0.026171   79442.502883  
min            0.000000   34900.000000  
25%            0.000000  129975.000000  
50%            0.000000  163000.000000  
75%            0.000000  214000.000000  
max            1.000000  755000.000000  

[8 rows x 271 columns]

In [6]:
columns = df_train.columns
columns

Index(['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BedroomAbvGr', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtUnfSF',
       'EnclosedPorch',
       ...
       'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth',
       'SaleType_WD', 'Street_Grvl', 'Street_Pave', 'Utilities_AllPub',
       'Utilities_NoSeWa', 'SalePrice'],
      dtype='object', length=271)

In [7]:
columns2 = df_test.columns
columns2

Index(['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BedroomAbvGr', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtUnfSF',
       'EnclosedPorch',
       ...
       'SaleType_ConLD', 'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New',
       'SaleType_Oth', 'SaleType_WD', 'Street_Grvl', 'Street_Pave',
       'Utilities_AllPub', 'Utilities_NoSeWa'],
      dtype='object', length=270)

In [8]:
df_data = pd.DataFrame(df_train)
df_data.head()

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0     856.0     854.0        0.0           3.0       706.0         0.0   
1    1262.0       0.0        0.0           3.0       978.0         0.0   
2     920.0     866.0        0.0           3.0       486.0         0.0   
3     961.0     756.0        0.0           3.0       216.0         0.0   
4    1145.0    1053.0        0.0           4.0       655.0         0.0   

   BsmtFullBath  BsmtHalfBath  BsmtUnfSF  EnclosedPorch    ...      \
0           1.0           0.0      150.0            0.0    ...       
1           0.0           1.0      284.0            0.0    ...       
2           1.0           0.0      434.0            0.0    ...       
3           1.0           0.0      540.0          272.0    ...       
4           1.0           0.0      490.0            0.0    ...       

   SaleType_ConLI  SaleType_ConLw  SaleType_New  SaleType_Oth  SaleType_WD  \
0             0.0             0.0           0.0           0.0          1.0   
1             0.0             0.0           0.0           0.0          1.0   
2             0.0             0.0           0.0           0.0          1.0   
3             0.0             0.0           0.0           0.0          1.0   
4             0.0             0.0           0.0           0.0          1.0   

   Street_Grvl  Street_Pave  Utilities_AllPub  Utilities_NoSeWa  SalePrice  
0          0.0          1.0               1.0               0.0     208500  
1          0.0          1.0               1.0               0.0     181500  
2          0.0          1.0               1.0               0.0     223500  
3          0.0          1.0               1.0               0.0     140000  
4          0.0          1.0               1.0               0.0     250000  

[5 rows x 271 columns]

In [9]:
df_data2 = pd.DataFrame(df_test)
df_data2.head()

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  BsmtFinSF1  BsmtFinSF2  \
0     896.0       0.0        0.0           2.0       468.0       144.0   
1    1329.0       0.0        0.0           3.0       923.0         0.0   
2     928.0     701.0        0.0           3.0       791.0         0.0   
3     926.0     678.0        0.0           3.0       602.0         0.0   
4    1280.0       0.0        0.0           2.0       263.0         0.0   

   BsmtFullBath  BsmtHalfBath  BsmtUnfSF  EnclosedPorch        ...         \
0           0.0           0.0      270.0            0.0        ...          
1           0.0           0.0      406.0            0.0        ...          
2           0.0           0.0      137.0            0.0        ...          
3           0.0           0.0      324.0            0.0        ...          
4           0.0           0.0     1017.0            0.0        ...          

   SaleType_ConLD  SaleType_ConLI  SaleType_ConLw  SaleType_New  SaleType_Oth  \
0             0.0             0.0             0.0           0.0           0.0   
1             0.0             0.0             0.0           0.0           0.0   
2             0.0             0.0             0.0           0.0           0.0   
3             0.0             0.0             0.0           0.0           0.0   
4             0.0             0.0             0.0           0.0           0.0   

   SaleType_WD  Street_Grvl  Street_Pave  Utilities_AllPub  Utilities_NoSeWa  
0          1.0          0.0          1.0               1.0               0.0  
1          1.0          0.0          1.0               1.0               0.0  
2          1.0          0.0          1.0               1.0               0.0  
3          1.0          0.0          1.0               1.0               0.0  
4          1.0          0.0          1.0               1.0               0.0  

[5 rows x 270 columns]

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df_train)
X_std = scaler.fit_transform(df_train)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df_test)
X_std2 = scaler.fit_transform(df_test)

In [12]:
from sklearn.decomposition import PCA
pca = PCA(n_components=270)
X_pca = pca.fit_transform(X_std)

In [13]:
from sklearn.decomposition import PCA
pca2 = PCA(n_components=270)
X_pca2 = pca2.fit_transform(X_std2)

In [14]:
X_pca[:10]

array([[  4.28385913e+00,   1.63681990e+00,  -2.26989034e+00, ...,
         -9.99291812e-16,   3.25722214e-16,  -1.34185473e-16],
       [ -1.80694854e-01,  -3.13389524e+00,  -6.29286513e-01, ...,
          2.04152965e-16,  -2.65516449e-16,  -1.82461036e-17],
       [  4.83440899e+00,   1.13387155e+00,  -1.65141689e+00, ...,
         -5.32015266e-16,  -1.00501794e-16,   2.84449514e-16],
       ..., 
       [  1.55209043e+00,  -3.19888164e+00,   1.27449798e+00, ...,
          4.85747872e-16,  -4.15357298e-17,   3.49741664e-16],
       [ -6.29161048e+00,   3.92997363e+00,   3.66795989e+00, ...,
          7.19503066e-16,   3.43831481e-16,  -2.18862123e-16],
       [ -4.85872467e+00,   1.80953659e+00,   9.66717509e-01, ...,
         -4.39590467e-17,  -8.71083626e-17,  -1.16900465e-16]])

In [15]:
X_pca2[:10]

array([[ -3.23563129e+00,  -3.11126575e+00,  -1.51369582e+00, ...,
         -4.17944937e-16,  -6.02371102e-17,   8.86761390e-17],
       [ -7.94053749e-01,  -4.39773926e+00,   1.36451022e+00, ...,
         -8.92451840e-17,  -5.63164693e-17,   2.00347603e-17],
       [  2.29298980e+00,   1.01748112e+00,  -2.40276116e+00, ...,
         -2.09972779e-17,  -6.02708526e-17,  -2.78825739e-17],
       ..., 
       [  1.69436900e+00,   2.20392838e+00,  -2.77275836e+00, ...,
         -2.51874366e-16,  -8.51980265e-17,   6.26117149e-17],
       [  1.56595247e+00,  -1.61707390e+00,  -1.53775308e+00, ...,
         -5.87943465e-17,   2.46886015e-16,  -5.62732249e-17],
       [ -2.44385037e+00,  -4.88969504e+00,  -1.74827426e+00, ...,
          1.78313252e-16,  -9.31018934e-17,   7.32244854e-17]])

In [16]:
print(np.cumsum(pca.explained_variance_ratio_))

[ 0.06835444  0.09823163  0.12314569  0.14285809  0.16066594  0.17739635
  0.1924226   0.20515777  0.2176808   0.2295095   0.24102338  0.25198544
  0.26262079  0.27305424  0.28322216  0.29321941  0.30293941  0.31225715
  0.32141424  0.33037645  0.33925992  0.3478713   0.35638644  0.36465686
  0.37278852  0.38086418  0.38888801  0.39678188  0.40457466  0.41234537
  0.41999696  0.42752568  0.43480232  0.44202263  0.4491867   0.4561567
  0.46307326  0.46989628  0.47661218  0.4832572   0.4898148   0.49630043
  0.50267881  0.50891263  0.5151289   0.52130282  0.52735301  0.5333159
  0.53917505  0.54498618  0.55072359  0.55634268  0.56194487  0.56746459
  0.57293856  0.57834973  0.58375683  0.58905438  0.59428073  0.599471
  0.60459376  0.60966846  0.61471883  0.61966956  0.62459401  0.62942749
  0.63421749  0.63895914  0.64368148  0.64838612  0.65302373  0.65763962
  0.66221667  0.66673258  0.67120731  0.67566283  0.6800671   0.68445302
  0.68872495  0.69298962  0.69722516  0.70145227  0.705

In [17]:
ratio = np.cumsum(pca.explained_variance_ratio_)
ratio

array([ 0.06835444,  0.09823163,  0.12314569,  0.14285809,  0.16066594,
        0.17739635,  0.1924226 ,  0.20515777,  0.2176808 ,  0.2295095 ,
        0.24102338,  0.25198544,  0.26262079,  0.27305424,  0.28322216,
        0.29321941,  0.30293941,  0.31225715,  0.32141424,  0.33037645,
        0.33925992,  0.3478713 ,  0.35638644,  0.36465686,  0.37278852,
        0.38086418,  0.38888801,  0.39678188,  0.40457466,  0.41234537,
        0.41999696,  0.42752568,  0.43480232,  0.44202263,  0.4491867 ,
        0.4561567 ,  0.46307326,  0.46989628,  0.47661218,  0.4832572 ,
        0.4898148 ,  0.49630043,  0.50267881,  0.50891263,  0.5151289 ,
        0.52130282,  0.52735301,  0.5333159 ,  0.53917505,  0.54498618,
        0.55072359,  0.55634268,  0.56194487,  0.56746459,  0.57293856,
        0.57834973,  0.58375683,  0.58905438,  0.59428073,  0.599471  ,
        0.60459376,  0.60966846,  0.61471883,  0.61966956,  0.62459401,
        0.62942749,  0.63421749,  0.63895914,  0.64368148,  0.64

In [18]:
count = 0
for i in range(len(ratio)):
    if ratio[i] < 0.8:
        count += 1
    else:
        print(count)
        break

108


In [19]:
X_pca = X_pca[:, :108]

In [56]:
X_pca2 = X_pca2[:, :108]

In [23]:
y = df_train.loc[:, ['SalePrice']].values

In [25]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [164]:
from sklearn.model_selection import train_test_split
X_pca_train, X_pca_test, y_train, y_test = train_test_split(X_pca, y, test_size = 0.3, random_state = 0)

In [165]:
lr.fit(X_pca_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [166]:
lr.intercept_

array([ 180902.07104763])

In [167]:
lr.coef_

array([[  1.51604329e+04,  -8.62652496e+02,   1.33319514e+04,
         -2.29167906e+03,  -2.80046135e+03,   4.33598978e+03,
         -3.50148711e+03,  -4.20076579e+03,  -2.85921585e+03,
         -1.21601843e+03,  -2.06811778e+03,  -1.05953117e+02,
          4.24598620e+02,   1.29003849e+02,   1.59219477e+03,
         -1.67171812e+03,   2.02190874e+03,   2.89440431e+03,
          2.55433000e+01,  -5.92938653e+02,  -6.14952408e+02,
          2.07110026e+03,  -7.68495692e+02,  -5.08922846e+02,
          1.11872124e+03,  -1.13371572e+03,   2.35105657e+03,
         -2.27424482e+03,  -3.33030488e+03,   2.24434970e+02,
          2.23865123e+03,   4.88412256e+02,  -1.66663913e+03,
         -2.40586004e+03,   2.19045212e+03,  -3.17750500e+01,
          9.05155392e+02,  -2.10066511e+03,   1.64134635e+03,
          3.34101045e+03,   7.99052126e+02,   1.45492370e+01,
          2.02399108e+03,  -2.12709752e+02,   7.57663739e+02,
         -4.16121998e+02,  -2.20160986e+02,   1.06328450e+03,
        

In [183]:
from sklearn.linear_model import Lasso
model_lasso = Lasso(alpha=2350)
model_lasso.fit(X_pca_train, y_train)

Lasso(alpha=2350, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [184]:
print('R^2')
print('train: %.3f' % model_lasso.score(X_pca_train, y_train))
print('test : %.3f' % model_lasso.score(X_pca_test, y_test))

R^2
train: 0.891
test : 0.784


In [185]:
model_lasso.coef_

array([  1.48218460e+04,  -4.27686204e+02,   1.25920003e+04,
        -1.70353549e+03,  -2.50860069e+03,   3.66234713e+03,
        -2.91894559e+03,  -3.41305874e+03,  -2.32219844e+03,
        -4.01523379e+02,  -8.41612877e+02,   0.00000000e+00,
         0.00000000e+00,  -0.00000000e+00,   2.24770998e+02,
        -2.06606518e+02,   4.16566157e+02,   6.69015664e+02,
        -0.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
         6.06790568e+02,  -5.61347552e+01,  -1.70601479e+02,
         4.09754360e+02,  -0.00000000e+00,   6.24150162e+02,
        -1.09944658e+03,  -2.05107452e+03,   0.00000000e+00,
         1.84506590e+01,   5.15995517e+02,  -0.00000000e+00,
        -1.23123591e+03,   4.35456381e+02,  -0.00000000e+00,
         0.00000000e+00,  -2.36445531e+01,   0.00000000e+00,
         1.15181279e+03,   0.00000000e+00,   0.00000000e+00,
         4.40876951e+02,  -0.00000000e+00,   0.00000000e+00,
        -0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
        -0.00000000e+00,

In [186]:
X_pca2.shape

(1459, 108)

In [187]:
y_pred = model_lasso.predict(X_pca2)

In [188]:
y_pred[:10]

array([ 117751.78906644,  177514.90515552,  188290.91617833,
        208862.95405428,  199975.73104258,  175347.46488596,
        187328.95741547,  173942.33089977,  198485.57727917,
        130621.96613419])

In [189]:
kaggle_df_test = pd.DataFrame({"Id":np.arange(1461, 2920), "SalePrice":y_pred})
kaggle_df_test.head()

Id      SalePrice
0  1461  117751.789066
1  1462  177514.905156
2  1463  188290.916178
3  1464  208862.954054
4  1465  199975.731043

In [190]:
kaggle_df_test.to_csv("housepriceC.csv", index=False)